### ISSUE TITLE
Not rendering correctly using xterm[-256color]

### ISSUE THREAD

**Issue by mpranjic** [anthepro/terminal-tetris#1]
Some lines are broken when running with `xterm`/`xterm-256color`.

![2017-10-28-113758_569x417_scrot](https://user-images.githubusercontent.com/2545452/32133248-762ee06a-bbd4-11e7-9a89-1d64804f5515.png)

When I set `TERM=screen` it renders correctly.

**Comment by anthepro** [comment]
I've tested it on Void using xterm, works as intended. I'll look into it.
